name: flutterfloor
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.1


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  floor: any
  flutter_slidable: ^4.0.0
  get: ^4.6.6
  sqflite: ^2.4.1
  local_auth: ^2.3.0
  double_back_to_close_app: ^2.1.0
  flutter_launcher_icons: ^0.14.3
  image_picker: ^1.1.2
  flutter_secure_storage: ^9.2.4
  theme_provider: ^0.6.0
  shared_preferences: ^2.5.2
  url_launcher: ^6.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  floor_generator: any
  build_runner: any

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"
  min_sdk_android: 21
  web:
    generate: true
    image_path: "assets/icon/icon.png"
  windows:
    generate: true
    image_path: "assets/icon/icon.png"
    icon_size: 48 
  macos:
    generate: true
    image_path: "assets/icon/icon.png"

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true
# To add assets to your application, add an assets section, like this:
  assets:
    - assets\icon\icon.png  
# dart run flutter_launcher_icons:generate
  fonts:
    - family: Schyler
      fonts:
      - asset: assets/fonts/Roboto-Italic-VariableFont_wdth,wght.ttf
      - asset: assets/fonts/Roboto-VariableFont_wdth,wght.ttf
        weight: 700
